//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoachSquad
    {
        public int CoachSquadID { get; set; }
        public Nullable<int> CoachID { get; set; }
        public Nullable<int> TrainingID { get; set; }
        public Nullable<int> MatchID { get; set; }
    
        public virtual Coachs Coachs { get; set; }
        public virtual Matches Matches { get; set; }
        public virtual Trainings Trainings { get; set; }
    }
}
