//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int ContractID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> CoachID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
    
        public virtual Agents Agents { get; set; }
        public virtual ContractTypeID ContractTypeID1 { get; set; }
        public virtual Players Players { get; set; }
        public virtual Coachs Coachs { get; set; }
    }
}
