//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp
{
    using System;
    
    public partial class GetPlayerStat_Result1
    {
        public Nullable<int> Column1 { get; set; }
        public Nullable<int> Column2 { get; set; }
        public Nullable<int> Column3 { get; set; }
        public Nullable<int> Column4 { get; set; }
        public Nullable<decimal> Column5 { get; set; }
        public Nullable<int> Column6 { get; set; }
    }
}
