//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mans
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mans()
        {
            this.Agents = new HashSet<Agents>();
            this.Players = new HashSet<Players>();
            this.Coachs = new HashSet<Coachs>();
        }
    
        public int ManID { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<short> Age { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public int NationalityID { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Weight { get; set; }
        public string Adress { get; set; }
        public string PhoneNumber { get; set; }
        public byte[] Photo { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> PersonalPositionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agents> Agents { get; set; }
        public virtual Nationaites Nationaites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Players> Players { get; set; }
        public virtual PersonalPosition PersonalPosition { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coachs> Coachs { get; set; }
    }
}
