//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FCEntities : DbContext
    {
        public FCEntities()
            : base("name=FCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agents> Agents { get; set; }
        public virtual DbSet<CoachSquad> CoachSquad { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<ContractTypeID> ContractTypeID { get; set; }
        public virtual DbSet<Mans> Mans { get; set; }
        public virtual DbSet<Matches> Matches { get; set; }
        public virtual DbSet<Nationaites> Nationaites { get; set; }
        public virtual DbSet<PersonalPosition> PersonalPosition { get; set; }
        public virtual DbSet<PlayerPositions> PlayerPositions { get; set; }
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<PlayerSquad> PlayerSquad { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Tournaments> Tournaments { get; set; }
        public virtual DbSet<Trainings> Trainings { get; set; }
        public virtual DbSet<PlayerInfo> PlayerInfo { get; set; }
        public virtual DbSet<Coachs> Coachs { get; set; }
    }
}
