//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerInfo
    {
        public int PlayerID { get; set; }
        public int ManID { get; set; }
        public Nullable<decimal> TransferCost { get; set; }
        public Nullable<short> PlayerNumber { get; set; }
        public string MiddleName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<short> Age { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<short> Height { get; set; }
        public Nullable<short> Weight { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string ContractTypeDescription { get; set; }
        public Nullable<int> ContractTypeID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
