//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Players()
        {
            this.Contracts = new HashSet<Contracts>();
            this.PlayerPositions = new HashSet<PlayerPositions>();
            this.PlayerSquad = new HashSet<PlayerSquad>();
        }
    
        public int PlayerID { get; set; }
        public int ManID { get; set; }
        public Nullable<decimal> TransferCost { get; set; }
        public Nullable<bool> TransferStatus { get; set; }
        public Nullable<bool> NationalTeamInvite { get; set; }
        public Nullable<bool> Injury { get; set; }
        public Nullable<short> PlayerNumber { get; set; }
        public Nullable<int> PlayerPositionsID { get; set; }
        public string ShirtName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual Mans Mans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerPositions> PlayerPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerSquad> PlayerSquad { get; set; }
    }
}
